# Generated by Django 3.0.6 on 2020-05-23 14:04

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptChrist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('note', models.TextField(default='I just responded to an Alter call to give my life to Christ', help_text='write a short not ie why you want to accept christ')),
                ('mode_to_reach_you', models.CharField(choices=[['Phone call', 'Phone Call'], ['Whatsapp', 'Whatsapp'], ['Sms', 'Sms'], ['Email', 'Email']], default='Phone call', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[['Prayer Request', 'Prayer Request'], ['General', 'General'], ['Testimonies', 'Testimonies'], ['Suggestions', 'Suggestions']], default='Prayer Request', max_length=20)),
                ('name', models.CharField(blank=True, help_text='optional', max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='%d-%m-%Y/images')),
                ('story', ckeditor.fields.RichTextField()),
                ('active', models.BooleanField(default=True, help_text='make this article pubic', verbose_name='make puplic')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('source', models.URLField(blank=True, help_text='source link', null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
    ]
