# Generated by Django 3.0.6 on 2020-05-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tof_app', '0002_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
