# Generated by Django 3.0.6 on 2020-05-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tof_app', '0003_auto_20200526_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[['event', 'Event'], ['anoycement', 'Anoucement']], default='event', max_length=15),
        ),
    ]
