# Generated by Django 3.0.6 on 2020-05-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tof_app', '0004_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
