# Generated by Django 2.2.10 on 2020-06-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tof_app', '0006_auto_20200526_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, help_text='input image url', null=True),
        ),
    ]
