# Generated by Django 2.2.10 on 2020-08-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tof_app', '0008_auto_20200613_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='select an image', null=True, upload_to='%d-%m-%Y/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, help_text='input image link from the net instead of raw image', null=True),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='request_type',
            field=models.CharField(choices=[['Prayer Request', 'Prayer Request'], ['Testimonies', 'Testimonies']], default='Prayer Request', max_length=20),
        ),
    ]
