# Generated by Django 3.0.6 on 2020-05-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_participate',
            field=models.BooleanField(default=True),
        ),
    ]
