# Generated by Django 3.0.6 on 2020-05-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200523_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_participate',
            field=models.BooleanField(default=False),
        ),
    ]
