# Generated by Django 3.0.6 on 2020-05-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20200523_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='can_participate',
            field=models.BooleanField(default=False),
        ),
    ]
