# Generated by Django 3.0.6 on 2020-05-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20200524_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='every_one',
            field=models.BooleanField(default=True, help_text='tick for every one untic to choose members'),
        ),
    ]
