# Generated by Django 3.0.6 on 2020-05-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_quiz_every_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_participate',
            field=models.BooleanField(default=False),
        ),
    ]
