# Generated by Django 3.0.6 on 2020-05-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_user_can_participate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='active',
            field=models.BooleanField(default=True, help_text='make puplic now'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='every_one',
            field=models.BooleanField(choices=[[True, 'ALL MEMBERS'], [False, 'NOT ALL MEMBERS']], default=True, verbose_name='participant'),
        ),
    ]
