# Generated by Django 3.0.6 on 2020-05-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_auto_20200525_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(blank=True, help_text='available topics', related_name='interested_students', to='classroom.Subject', verbose_name='available topic(s)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_participate',
            field=models.BooleanField(default=True),
        ),
    ]
