# Generated by Django 3.0.6 on 2020-05-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_auto_20200525_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='interests',
        ),
    ]
