# Generated by Django 2.2.10 on 2020-06-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_auto_20200609_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='subject',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='active',
            field=models.BooleanField(default=True, help_text='make this quize public now'),
        ),
    ]
