# Generated by Django 2.2.10 on 2020-08-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_remove_quiz_every_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='every_one',
            field=models.BooleanField(default=True, verbose_name='participant'),
        ),
    ]
